export { default as logo } from "./civilsa.jpeg"
export { default as school } from "./school.jpg"
export { default as busines } from "./busines.jpg"
export { default as farm } from "./farming.jpg"
export { default as biz } from "./biz.jpeg"
export { default as build } from "./build.jpg"
export { default as bizna } from "./bizna.jpg"
export { default as work } from "./work.jpg"
export {default as james} from "./james.webp"